# Generated by Django 6.0 on 2026-02-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_customuser_is_farmer_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('berry', 'Berry'), ('strawberry', 'Strawberry'), ('vegetable', 'Vegetable'), ('wheat', 'Wheat')], default='fruit', max_length=20),
        ),
    ]
