# Generated by Django 6.0.5 on 2026-05-23 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market_location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='priced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(db_index=True)),
                ('commodity_type', models.CharField(db_index=True, max_length=80)),
                ('variety', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('market_location', models.CharField(db_index=True, max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(default='amis.pk', max_length=120)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-price_date', 'commodity_type', 'variety', 'market_location'],
                'constraints': [models.UniqueConstraint(fields=('price_date', 'commodity_type', 'variety', 'market_location'), name='uniq_marketprice_day_commodity_variety_location')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='price_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_products', to='shop.marketprice'),
        ),
    ]
