# Generated by Django 6.0.5 on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_market_location_product_priced_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketprice',
            name='uniq_marketprice_day_commodity_variety_location',
        ),
        migrations.RemoveField(
            model_name='marketprice',
            name='region',
        ),
        migrations.RemoveField(
            model_name='marketprice',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variety',
        ),
        migrations.AlterModelOptions(
            name='marketprice',
            options={'ordering': ['-price_date', 'commodity_type', 'market_location']},
        ),
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.UniqueConstraint(
                fields=('price_date', 'commodity_type', 'market_location'),
                name='uniq_marketprice_day_commodity_location',
            ),
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_seller_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_seller_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('seller', 'reviewer')},
            },
        ),
    ]
